FROM node:21-alpine3.18 AS builder

WORKDIR /opt/builder

COPY package.json .

RUN npm i

COPY ./ ./

ENTRYPOINT [ "sh", "-c", "npm run generate \
    && npm run migrate \
    && npm run build \
    && cp -r /opt/builder/src/generated dist/ \
    && cp /opt/builder/.env dist/" ]